#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${LOG_LEVEL:-}" ]; then
    export LOG_LEVEL="debug"
fi

if [ -z "${DB_PORT:-}" ]; then
    export DB_PORT="8081"
fi

export HTTP_PORT="8000"

if [ -z "${HTTP_WORKERS:-}" ]; then
    export HTTP_WORKERS=1
fi

export PYTHONPATH=/app

echo "Waiting for Database to be available..."
while ! nc -z db ${DB_PORT}; do
    sleep 0.1
done
echo "Database is up and running!"

echo "Starting API Server..."

gunicorn_command="gunicorn src.main:app \
    --bind 0.0.0.0:$HTTP_PORT \
    --workers $HTTP_WORKERS \
    --timeout 120 \
    --log-level $LOG_LEVEL \
    --reload"

exec $gunicorn_command

echo "API Server is up and running!"
