steps:
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA', '-f', 'docker/prod/Dockerfile', '.']
    dir: '.'

  - id: 'Push to GCR'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cargopulse-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA'
      - '--region'
      - 'europe-west8'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA'
