steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA', '-f', 'docker/prod/Dockerfile', '.']
    dir: '.'

images:
  - 'gcr.io/$PROJECT_ID/cargopulse-api:$SHORT_SHA'
