version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: cargopulse-api
    volumes:
      - .:/app:z
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cargopulse

  db:
    image: google/cloud-sdk:470.0.0-emulators
    container_name: cargopulse-db
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8081 --data-dir=/opt/data --quiet
    expose:
      - "8081"
    environment:
      - CLOUDSDK_CORE_PROJECT=dummy-project
    volumes:
      - cargopulse_db_data:/opt/data
    env_file:
      - ./.env
    networks:
      - cargopulse

volumes:
  cargopulse_db_data:


networks:
    cargopulse:
      driver: bridge
