#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${LOG_LEVEL:-}" ]; then
    export LOG_LEVEL="debug"
fi

export HTTP_PORT="80"

if [ -z "${HTTP_WORKERS:-}" ]; then
    export HTTP_WORKERS=1
fi

export PYTHONPATH=/app

echo "Starting API Server..."

gunicorn_command="gunicorn src.main:app \
    --bind 0.0.0.0:$HTTP_PORT \
    --workers $HTTP_WORKERS \
    --timeout 120 \
    --log-level $LOG_LEVEL"

exec $gunicorn_command

echo "API Server is up and running!"
